"""Templates for project bootstrapping."""

from dataclasses import dataclass
from typing import Dict


@dataclass
class ProjectTemplate:
    """Template configuration for a project type."""
    marker_files: list[str]
    env_dir: str
    test_dirs: list[str]
    test_patterns: list[str]
    dep_install_commands: list[dict]
    test_command: str
    test_dep: str
    scaffold_test: str


PYTHON_TEST_TEMPLATE = '''"""Sample test — auto-generated by goal."""


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    import {package_name}  # noqa: F401
'''

NODE_TEST_TEMPLATE = '''// Sample test — auto-generated by goal
describe('Placeholder', () => {{
  test('should pass', () => {{
    expect(true).toBe(true);
  }});
}});
'''

RUST_TEST_TEMPLATE = '''// Sample test — auto-generated by goal
#[cfg(test)]
mod tests {{
    #[test]
    fn test_placeholder() {{
        assert!(true);
    }}
}}
'''

GO_TEST_TEMPLATE = '''// Sample test — auto-generated by goal
package main

import "testing"

func TestPlaceholder(t *testing.T) {{
    // Placeholder test
}}
'''


PROJECT_TEMPLATES: Dict[str, ProjectTemplate] = {
    'python': ProjectTemplate(
        marker_files=['pyproject.toml', 'setup.py', 'setup.cfg', 'requirements.txt'],
        env_dir='.venv',
        test_dirs=['tests', 'test'],
        test_patterns=['test_*.py', '*_test.py'],
        dep_install_commands=[
            {'condition': 'pyproject.toml', 'cmd': '{python} -m pip install -e ".[dev]"', 'fallback': '{python} -m pip install -e .'},
            {'condition': 'requirements.txt', 'cmd': '{python} -m pip install -r requirements.txt'},
            {'condition': 'requirements-dev.txt', 'cmd': '{python} -m pip install -r requirements-dev.txt'},
        ],
        test_command='pytest',
        test_dep='pytest',
        scaffold_test=PYTHON_TEST_TEMPLATE,
    ),
    'nodejs': ProjectTemplate(
        marker_files=['package.json'],
        env_dir='node_modules',
        test_dirs=['test', 'tests', '__tests__', 'spec'],
        test_patterns=['*.test.js', '*.spec.js', '*.test.ts', '*.spec.ts'],
        dep_install_commands=[
            {'condition': 'yarn.lock', 'cmd': 'yarn install'},
            {'condition': 'pnpm-lock.yaml', 'cmd': 'pnpm install'},
            {'condition': 'package-lock.json', 'cmd': 'npm install'},
            {'condition': 'package.json', 'cmd': 'npm install'},
        ],
        test_command='npm test',
        test_dep='',
        scaffold_test=NODE_TEST_TEMPLATE,
    ),
    'rust': ProjectTemplate(
        marker_files=['Cargo.toml'],
        env_dir='target',
        test_dirs=['tests', 'src'],
        test_patterns=['*.rs'],
        dep_install_commands=[
            {'condition': 'Cargo.toml', 'cmd': 'cargo build'},
        ],
        test_command='cargo test',
        test_dep='',
        scaffold_test=RUST_TEST_TEMPLATE,
    ),
    'go': ProjectTemplate(
        marker_files=['go.mod'],
        env_dir='',
        test_dirs=['.'],
        test_patterns=['*_test.go'],
        dep_install_commands=[
            {'condition': 'go.mod', 'cmd': 'go mod tidy'},
        ],
        test_command='go test ./...',
        test_dep='',
        scaffold_test=GO_TEST_TEMPLATE,
    ),
    'ruby': ProjectTemplate(
        marker_files=['Gemfile'],
        env_dir='vendor/bundle',
        test_dirs=['test', 'spec'],
        test_patterns=['*_test.rb', '*_spec.rb'],
        dep_install_commands=[
            {'condition': 'Gemfile.lock', 'cmd': 'bundle install'},
            {'condition': 'Gemfile', 'cmd': 'bundle install'},
        ],
        test_command='bundle exec rake test',
        test_dep='',
        scaffold_test='',
    ),
    'php': ProjectTemplate(
        marker_files=['composer.json'],
        env_dir='vendor',
        test_dirs=['tests', 'test'],
        test_patterns=['*Test.php', '*Test.php'],
        dep_install_commands=[
            {'condition': 'composer.lock', 'cmd': 'composer install'},
            {'condition': 'composer.json', 'cmd': 'composer install'},
        ],
        test_command='vendor/bin/phpunit',
        test_dep='',
        scaffold_test='',
    ),
    'dotnet': ProjectTemplate(
        marker_files=['*.csproj', '*.sln'],
        env_dir='',
        test_dirs=['.', 'tests'],
        test_patterns=['*.cs'],
        dep_install_commands=[
            {'condition': '*.csproj', 'cmd': 'dotnet restore'},
            {'condition': '*.sln', 'cmd': 'dotnet restore'},
        ],
        test_command='dotnet test',
        test_dep='',
        scaffold_test='',
    ),
    'java': ProjectTemplate(
        marker_files=['pom.xml', 'build.gradle'],
        env_dir='target',
        test_dirs=['src/test/java'],
        test_patterns=['*Test.java'],
        dep_install_commands=[
            {'condition': 'pom.xml', 'cmd': 'mvn dependency:resolve'},
            {'condition': 'build.gradle', 'cmd': 'gradle dependencies'},
        ],
        test_command='mvn test',
        test_dep='',
        scaffold_test='',
    ),
}

# For backward compatibility
PROJECT_BOOTSTRAP = {
    name: {
        'marker_files': t.marker_files,
        'env_dir': t.env_dir,
        'test_dirs': t.test_dirs,
        'test_patterns': t.test_patterns,
        'dep_install_commands': t.dep_install_commands,
        'test_command': t.test_command,
        'test_dep': t.test_dep,
        'scaffold_test': t.scaffold_test,
    }
    for name, t in PROJECT_TEMPLATES.items()
}
