"""Project environment bootstrapping and test scaffolding.

Detects project types (including 1-level-deep subfolders), ensures environments
are properly initialized (venv, deps), and scaffolds sample tests when missing.
"""

import os
import subprocess
import shutil
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import click

from goal.project_doctor import diagnose_and_report
from goal.installers import PackageManagerBroker
from goal.toml_validation import get_tomllib

# Import from refactored bootstrap module for backward compatibility
from goal.bootstrap.detector import detect_project_types_deep, guess_package_name
from goal.bootstrap.templates import PROJECT_BOOTSTRAP
from goal.bootstrap.installer import (
    ensure_project_environment,
    _install_python_deps_broker,
)
from goal.bootstrap.configurator import scaffold_test_file as _scaffold_test_file_impl
from goal.bootstrap.costs_badge import _generate_costs_badge, _install_costs_package
from goal.bootstrap.pyproject_costs_setup import (
    _ensure_costs_config,
    _ensure_env_template,
)

logger = logging.getLogger(__name__)

# =============================================================================
# Project bootstrap configuration per language/framework
# =============================================================================

PROJECT_BOOTSTRAP = {
    "python": {
        "marker_files": ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"],
        "env_dir": ".venv",
        "test_dirs": ["tests", "test"],
        "test_patterns": ["test_*.py", "*_test.py"],
        "dep_install_commands": [
            # Order matters: try pyproject.toml editable install first, then requirements.txt
            {
                "condition": "pyproject.toml",
                "cmd": '{python} -m pip install -e ".[dev]"',
                "fallback": "{python} -m pip install -e .",
            },
            {
                "condition": "requirements.txt",
                "cmd": "{python} -m pip install -r requirements.txt",
            },
            {
                "condition": "requirements-dev.txt",
                "cmd": "{python} -m pip install -r requirements-dev.txt",
            },
        ],
        "test_command": "pytest",
        "test_dep": "pytest",
        "scaffold_test": '''"""Sample test — auto-generated by goal."""


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    import {package_name}  # noqa: F401
''',
    },
    "nodejs": {
        "marker_files": ["package.json"],
        "env_dir": "node_modules",
        "test_dirs": ["test", "tests", "__tests__", "spec"],
        "test_patterns": ["*.test.js", "*.spec.js", "*.test.ts", "*.spec.ts"],
        "dep_install_commands": [
            {"condition": "yarn.lock", "cmd": "yarn install"},
            {"condition": "pnpm-lock.yaml", "cmd": "pnpm install"},
            {"condition": "package-lock.json", "cmd": "npm install"},
            {"condition": "package.json", "cmd": "npm install"},
        ],
        "test_command": "npm test",
        "test_dep": "jest",
        "scaffold_test": """// Sample test — auto-generated by goal.

describe('{package_name}', () => {{
  test('placeholder test', () => {{
    expect(true).toBe(true);
  }});
}});
""",
    },
    "rust": {
        "marker_files": ["Cargo.toml"],
        "env_dir": "target",
        "test_dirs": ["tests"],
        "test_patterns": ["*.rs"],
        "dep_install_commands": [
            {"condition": "Cargo.toml", "cmd": "cargo build"},
        ],
        "test_command": "cargo test",
        "test_dep": None,
        "scaffold_test": """// Sample test — auto-generated by goal.

#[cfg(test)]
mod tests {{
    #[test]
    fn placeholder_test() {{
        assert!(true);
    }}
}}
""",
    },
    "go": {
        "marker_files": ["go.mod"],
        "env_dir": None,
        "test_dirs": ["."],
        "test_patterns": ["*_test.go"],
        "dep_install_commands": [
            {"condition": "go.mod", "cmd": "go mod download"},
        ],
        "test_command": "go test ./...",
        "test_dep": None,
        "scaffold_test": """// Sample test — auto-generated by goal.
package main

import "testing"

func TestPlaceholder(t *testing.T) {{
\tif false {{
\t\tt.Error("placeholder test failed")
\t}}
}}
""",
    },
    "ruby": {
        "marker_files": ["Gemfile", "*.gemspec"],
        "env_dir": "vendor/bundle",
        "test_dirs": ["spec", "test"],
        "test_patterns": ["*_spec.rb", "test_*.rb", "*_test.rb"],
        "dep_install_commands": [
            {"condition": "Gemfile", "cmd": "bundle install"},
        ],
        "test_command": "bundle exec rspec",
        "test_dep": "rspec",
        "scaffold_test": """# Sample test — auto-generated by goal.

RSpec.describe '{package_name}' do
  it 'placeholder test' do
    expect(true).to be true
  end
end
""",
    },
    "php": {
        "marker_files": ["composer.json"],
        "env_dir": "vendor",
        "test_dirs": ["tests", "test"],
        "test_patterns": ["*Test.php", "test_*.php"],
        "dep_install_commands": [
            {"condition": "composer.json", "cmd": "composer install"},
        ],
        "test_command": "composer test",
        "test_dep": "phpunit/phpunit",
        "scaffold_test": """<?php
// Sample test — auto-generated by goal.

use PHPUnit\\Framework\\TestCase;

class PlaceholderTest extends TestCase
{{
    public function testPlaceholder(): void
    {{
        $this->assertTrue(true);
    }}
}}
""",
    },
    "dotnet": {
        "marker_files": ["*.csproj", "*.fsproj", "*.sln"],
        "env_dir": "bin",
        "test_dirs": ["Tests", "tests"],
        "test_patterns": ["*Tests.cs", "*Test.cs"],
        "dep_install_commands": [
            {"condition": "*.csproj", "cmd": "dotnet restore"},
            {"condition": "*.sln", "cmd": "dotnet restore"},
        ],
        "test_command": "dotnet test",
        "test_dep": None,
        "scaffold_test": """// Sample test — auto-generated by goal.
using Xunit;

namespace {package_name}.Tests
{{
    public class PlaceholderTest
    {{
        [Fact]
        public void Placeholder_ShouldPass()
        {{
            Assert.True(true);
        }}
    }}
}}
""",
    },
    "java": {
        "marker_files": ["pom.xml", "build.gradle", "build.gradle.kts"],
        "env_dir": "target",
        "test_dirs": ["src/test/java", "src/test"],
        "test_patterns": ["*Test.java", "*Tests.java"],
        "dep_install_commands": [
            {"condition": "pom.xml", "cmd": "mvn dependency:resolve"},
            {"condition": "build.gradle", "cmd": "gradle dependencies"},
            {"condition": "build.gradle.kts", "cmd": "gradle dependencies"},
        ],
        "test_command": "mvn test",
        "test_dep": None,
        "scaffold_test": """// Sample test — auto-generated by goal.
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PlaceholderTest {{
    @Test
    void placeholderTest() {{
        assertTrue(true);
    }}
}}
""",
    },
}


# =============================================================================
# Detection helpers
# =============================================================================


def _match_marker(base: Path, pattern: str) -> bool:
    """Check if a marker file/pattern exists under *base*."""
    if "*" in pattern:
        return bool(list(base.glob(pattern)))
    return (base / pattern).exists()


def detect_project_types_deep(
    root: Optional[Path] = None, max_depth: int = 1
) -> Dict[str, List[Path]]:
    """Detect project types in *root* and up to *max_depth* subfolder levels.

    Returns a dict mapping project type → list of directories where it was found.
    """
    if root is None:
        root = Path(".")
    root = root.resolve()

    results: Dict[str, List[Path]] = {}

    dirs_to_scan = [root]
    if max_depth >= 1:
        try:
            for child in sorted(root.iterdir()):
                if child.is_dir() and not child.name.startswith("."):
                    dirs_to_scan.append(child)
        except PermissionError:
            pass

    for scan_dir in dirs_to_scan:
        for ptype, cfg in PROJECT_BOOTSTRAP.items():
            for marker in cfg["marker_files"]:
                if _match_marker(scan_dir, marker):
                    results.setdefault(ptype, []).append(scan_dir)
                    break

    return results


# =============================================================================
# Environment bootstrapping
# =============================================================================


def _find_python_bin(project_dir: Path) -> str:
    """Return the best python binary path for a project directory."""
    # Check common venv names in order of preference
    for venv_name in [".venv", "venv", "env"]:
        venv_python = project_dir / venv_name / "bin" / "python"
        if venv_python.exists():
            return str(venv_python)
    # Check active virtualenv
    venv_env = os.environ.get("VIRTUAL_ENV")
    if venv_env:
        candidate = Path(venv_env) / "bin" / "python"
        if candidate.exists():
            return str(candidate)
    # sys.executable
    import sys

    return sys.executable


def _read_openrouter_api_key(env_file: Path) -> str:
    """Extract OPENROUTER_API_KEY from a .env file."""
    try:
        content = env_file.read_text(encoding="utf-8")
    except OSError as exc:
        logger.debug("Failed to read %s: %s", env_file, exc)
        return ""

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].strip()

        key_name, sep, value = stripped.partition("=")
        if not sep or key_name.strip() != "OPENROUTER_API_KEY":
            continue

        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1].strip()
        return value

    return ""


def _find_openrouter_api_key(project_dir: Path) -> Tuple[Optional[Path], str]:
    """Find an OpenRouter API key in the environment or any ancestor .env file."""
    env_key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    if env_key:
        return None, env_key

    search_dir = project_dir.resolve()
    while True:
        candidate = search_dir / ".env"
        if candidate.exists():
            api_key = _read_openrouter_api_key(candidate)
            if api_key:
                return candidate, api_key

        if search_dir == search_dir.parent:
            break
        search_dir = search_dir.parent

    return None, ""


def _find_git_root(project_dir: Path) -> Optional[Path]:
    """Find the git repository root for a project directory."""
    current = project_dir.resolve()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    return None


def refresh_test_dependencies(
    project_types: List[str],
    *,
    yes: bool = True,
    dry_run: bool = False,
) -> None:
    """Re-ensure test runner deps after dependency upgrades (e.g. uv sync --upgrade)."""
    if dry_run or "python" not in project_types:
        return

    cfg = PROJECT_BOOTSTRAP.get("python", {})
    test_dep = cfg.get("test_dep")
    if not test_dep:
        return

    for project_dir in detect_project_types_deep().get("python", [Path.cwd()]):
        project_dir = Path(project_dir)
        has_uv = bool(shutil.which("uv")) and (
            (project_dir / "uv.lock").exists() or (project_dir / "pyproject.toml").exists()
        )

        if has_uv:
            check = subprocess.run(
                ["uv", "run", "python", "-c", f"import {test_dep}"],
                capture_output=True,
                text=True,
                cwd=str(project_dir),
            )
            if check.returncode == 0:
                continue
            click.echo(
                click.style(
                    f"  Reinstalling {test_dep} after dependency upgrade (uv project)",
                    fg="cyan",
                )
            )
            install = subprocess.run(
                ["uv", "pip", "install", test_dep],
                capture_output=True,
                text=True,
                cwd=str(project_dir),
            )
            if install.returncode != 0:
                click.echo(
                    click.style(
                        f"  ⚠ Could not reinstall {test_dep} via uv pip",
                        fg="yellow",
                    )
                )
            continue

        python_bin = _find_python_bin(project_dir)
        _ensure_python_test_dependency(project_dir, python_bin, test_dep)


def _pytest_addopts_satisfied(project_dir: Path, python_bin: str) -> bool:
    """Check pytest can actually collect, not just import.

    `import pytest` succeeding doesn't mean pytest can run: pyproject.toml's
    own `addopts` (e.g. `-n auto`) can require a plugin (pytest-xdist) that
    lives under `[project.optional-dependencies] dev` rather than being a
    hard dependency. A bare uv/pip sync that skips extras leaves `pytest`
    importable but every actual test run failing with argparse's
    "unrecognized arguments" before a single test collects -- reported here
    as a false "test dependency ready" (2026-07-06: code2llm's `-n auto`
    addopts silently broke `goal -a -y` this way after a plain `uv sync`).
    """
    probe = subprocess.run(
        [python_bin, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider"],
        capture_output=True,
        text=True,
        cwd=str(project_dir),
        timeout=60,
    )
    return "unrecognized arguments" not in probe.stderr


def _ensure_python_test_dependency(
    project_dir: Path, python_bin: str, test_dep: Optional[str]
) -> bool:
    """Ensure the Python test runner dependency is available in the project venv."""
    if not test_dep:
        return True

    def addopts_ok() -> bool:
        return test_dep != "pytest" or _pytest_addopts_satisfied(project_dir, python_bin)

    check_result = subprocess.run(
        [python_bin, "-c", f"import {test_dep}; print({test_dep}.__version__)"],
        capture_output=True,
        text=True,
        cwd=str(project_dir),
    )
    if check_result.returncode == 0 and addopts_ok():
        version = check_result.stdout.strip()
        if version:
            click.echo(
                click.style(f"  ✓ {test_dep} already installed ({version})", fg="green")
            )
        else:
            click.echo(click.style(f"  ✓ {test_dep} already installed", fg="green"))
        return True

    click.echo(click.style(f"  Installing test dependency: {test_dep}", fg="cyan"))
    install_result = subprocess.run(
        [python_bin, "-m", "pip", "install", test_dep],
        capture_output=True,
        text=True,
        cwd=str(project_dir),
    )
    if install_result.returncode == 0 and not addopts_ok():
        # pytest itself is fine, but the project's own addopts still can't
        # run -- a required plugin lives in a dev/optional extras group
        # that the bare install above doesn't pull in. Pull the full group.
        install_result = subprocess.run(
            [python_bin, "-m", "pip", "install", "-e", ".[dev]"],
            capture_output=True,
            text=True,
            cwd=str(project_dir),
        )
        if install_result.returncode == 0 and not addopts_ok():
            click.echo(
                click.style(
                    f"  ⚠ {test_dep} installed but the project's own pytest addopts "
                    "still fail to run (check for a missing plugin under "
                    "[project.optional-dependencies] in pyproject.toml)",
                    fg="yellow",
                )
            )
            return False

    if install_result.returncode != 0:
        click.echo(
            click.style(
                f"  ⚠ Could not install test dependency: {test_dep}", fg="yellow"
            )
        )
        return False

    click.echo(click.style(f"  ✓ Test dependency installed ({test_dep})", fg="green"))
    return True


def _ensure_python_env(project_dir: Path, cfg: dict, yes: bool) -> bool:
    """Set up Python project environment: venv, pip, costs, deps, test deps."""
    venv_path = project_dir / ".venv"
    if not venv_path.exists():
        if not yes:
            click.echo(
                click.style(
                    f"\n⚠  No virtual environment found in {project_dir}", fg="yellow"
                )
            )
            if not click.confirm(
                click.style("Create .venv and install dependencies?", fg="cyan"),
                default=True,
            ):
                return True  # user declined, not a failure
        click.echo(click.style(f"  Creating .venv in {project_dir} ...", fg="cyan"))
        import sys

        result = subprocess.run(
            [sys.executable, "-m", "venv", str(venv_path)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            click.echo(
                click.style(
                    f"  ✗ Failed to create venv: {result.stderr.strip()}", fg="red"
                )
            )
            return False
        click.echo(click.style("  ✓ Created .venv", fg="green"))

    python_bin = _find_python_bin(project_dir)

    # Upgrade pip
    subprocess.run(
        [python_bin, "-m", "pip", "install", "--upgrade", "pip"],
        capture_output=True,
        text=True,
        cwd=str(project_dir),
    )

    # Install costs package for AI tracking
    _ensure_costs_installed(project_dir, python_bin)

    # Install deps using broker first (preferred), fallback to legacy
    broker_success = _install_python_deps_broker(project_dir, extras=["dev"])
    if not broker_success:
        _install_python_deps(project_dir, cfg, python_bin)

    test_dep = cfg.get("test_dep")
    return _ensure_python_test_dependency(project_dir, python_bin, test_dep)


def _should_skip_install(project_dir: Path, markers: List[str]) -> bool:
    """Check if dependency installation can be skipped based on file modification times."""
    venv_dir = project_dir / ".venv"
    if not venv_dir.exists():
        return False

    sync_marker = venv_dir / ".goal_deps_ok"
    if not sync_marker.exists():
        return False

    marker_mtime = sync_marker.stat().st_mtime
    for marker in markers:
        config_file = project_dir / marker
        if config_file.exists() and config_file.stat().st_mtime > marker_mtime:
            return False

    return True


def _install_python_deps(project_dir: Path, cfg: dict, python_bin: str) -> None:
    """Run the first matching dependency install command for a Python project.

    Optimized to use 'uv' if available and skip if dependencies are already synced.
    """
    marker_files = cfg.get("marker_files", [])
    if _should_skip_install(project_dir, marker_files):
        # click.echo(click.style("  ✓ Dependencies already synced (skipping install)", fg='green'))
        return

    import shutil

    has_uv = bool(shutil.which("uv"))

    for dep_cfg in cfg["dep_install_commands"]:
        if not _match_marker(project_dir, dep_cfg["condition"]):
            continue

        cmd = dep_cfg["cmd"].format(python=python_bin)

        # Optimize with uv if available
        if has_uv and "-m pip install" in cmd:
            cmd = cmd.replace(f"{python_bin} -m pip install", "uv pip install")
            # uv doesn't need the python prefix if we are in the right env or using --python
            if not cmd.startswith("uv"):
                cmd = f"uv pip install {cmd.split('install ', 1)[1]}"

        click.echo(click.style(f"  Installing deps: {cmd}", fg="cyan"))
        result = subprocess.run(
            cmd, shell=True, cwd=str(project_dir), capture_output=True, text=True
        )

        if result.returncode != 0:
            fallback = dep_cfg.get("fallback")
            if fallback:
                cmd = fallback.format(python=python_bin)
                click.echo(click.style(f"  Retrying: {cmd}", fg="yellow"))
                result = subprocess.run(
                    cmd,
                    shell=True,
                    cwd=str(project_dir),
                    capture_output=True,
                    text=True,
                )

            if result.returncode != 0:
                click.echo(
                    click.style(
                        f"  ⚠  Dependency install had issues (exit {result.returncode})",
                        fg="yellow",
                    )
                )
                if result.stderr:
                    click.echo(
                        click.style(
                            f"    Error: {result.stderr.strip().splitlines()[-1]}",
                            fg="red",
                        )
                    )
                return

        # Mark as synced
        venv_dir = project_dir / ".venv"
        if venv_dir.exists():
            (venv_dir / ".goal_deps_ok").touch()

        click.echo(click.style("  ✓ Dependencies installed", fg="green"))
        break  # Only run the first matching dep install


def _install_python_deps_broker(
    project_dir: Path, extras: Optional[List[str]] = None
) -> bool:
    """Install Python dependencies using PackageManagerBroker.

    Delegates to intelligent broker that auto-detects and prioritizes
    fast package managers (uv, pdm, poetry) with pip as fallback.

    Args:
        project_dir: Project root directory
        extras: Optional list of extra dependency groups (e.g., ["dev", "test"])

    Returns:
        True if installation succeeded, False otherwise
    """
    broker = PackageManagerBroker(str(project_dir))
    try:
        result = broker.install(extras=extras, auto_install_uv=True)
        return result.success
    except RuntimeError as e:
        click.echo(click.style(f"  ⚠  {e}", fg="yellow"))
        return False


def _ensure_generic_env(
    project_dir: Path, project_type: str, cfg: dict, yes: bool
) -> bool:
    """Set up a non-Python project environment (Node, Rust, Go, etc.)."""
    env_dir = cfg.get("env_dir")
    if env_dir and (project_dir / env_dir).exists():
        return True  # Already set up

    needs_install = env_dir and not (project_dir / env_dir).exists()
    if not needs_install:
        for dep_cfg in cfg["dep_install_commands"]:
            if _match_marker(project_dir, dep_cfg["condition"]):
                needs_install = True
                break

    if not needs_install:
        return True

    if not yes:
        click.echo(
            click.style(
                f"\n⚠  Dependencies not installed for {project_type} project in {project_dir}",
                fg="yellow",
            )
        )
        if not click.confirm(
            click.style("Install dependencies?", fg="cyan"), default=True
        ):
            return True

    for dep_cfg in cfg["dep_install_commands"]:
        if not _match_marker(project_dir, dep_cfg["condition"]):
            continue
        cmd = dep_cfg["cmd"]
        tool = cmd.split()[0]
        if not shutil.which(tool):
            click.echo(
                click.style(f"  ⚠  '{tool}' not found in PATH, skipping", fg="yellow")
            )
            continue
        click.echo(click.style(f"  Installing deps: {cmd}", fg="cyan"))
        result = subprocess.run(
            cmd, shell=True, cwd=str(project_dir), capture_output=True, text=True
        )
        if result.returncode == 0:
            click.echo(click.style("  ✓ Dependencies installed", fg="green"))
        else:
            click.echo(
                click.style(
                    f"  ⚠  Install had issues (exit {result.returncode})", fg="yellow"
                )
            )
        break

    return True


def ensure_project_environment(
    project_dir: Path, project_type: str, yes: bool = False
) -> bool:
    """Ensure the project environment is properly set up.

    For Python: creates .venv if missing, installs dependencies.
    For Node: runs npm/yarn/pnpm install if node_modules missing.
    For others: runs the appropriate dependency install command.

    Returns True if environment is ready, False on failure.
    """
    cfg = PROJECT_BOOTSTRAP.get(project_type)
    if not cfg:
        return True

    project_dir = project_dir.resolve()

    if project_type == "python":
        return _ensure_python_env(project_dir, cfg, yes)
    return _ensure_generic_env(project_dir, project_type, cfg, yes)


# =============================================================================
# Test scaffolding
# =============================================================================


def find_existing_tests(project_dir: Path, project_type: str) -> List[Path]:
    """Find existing test files for the given project type."""
    cfg = PROJECT_BOOTSTRAP.get(project_type)
    if not cfg:
        return []

    found: List[Path] = []
    for test_dir_name in cfg["test_dirs"]:
        test_dir = project_dir / test_dir_name
        if not test_dir.exists():
            continue
        for pattern in cfg["test_patterns"]:
            found.extend(test_dir.rglob(pattern))

    return found


# Test file name templates per project type.
# Value is a format string receiving {package_name}; use 'test_dir' or 'project_dir' as base.
_TEST_FILE_NAMES = {
    "python": ("test_dir", "test_{package_name}.py"),
    "nodejs": ("test_dir", "{package_name}.test.js"),
    "rust": ("test_dir", "placeholder_test.rs"),
    "go": ("project_dir", "placeholder_test.go"),
    "ruby": ("test_dir", "{package_name}_spec.rb"),
    "php": ("test_dir", "PlaceholderTest.php"),
    "dotnet": ("test_dir", "PlaceholderTest.cs"),
    "java": ("test_dir", "PlaceholderTest.java"),
}


def _resolve_scaffold_test_path(
    project_dir: Path, project_type: str, cfg: dict, package_name: str
) -> Optional[Path]:
    template = _TEST_FILE_NAMES.get(project_type)
    if not template:
        return None

    test_dir_name = cfg["test_dirs"][0]
    base_key, name_fmt = template
    if project_dir.name == test_dir_name:
        base = project_dir
    else:
        test_dir = project_dir / test_dir_name
        base = test_dir if base_key == "test_dir" else project_dir
    return base / name_fmt.format(package_name=package_name)


def scaffold_test(
    project_dir: Path, project_type: str, yes: bool = False
) -> Optional[Path]:
    """Create a sample test file if no tests exist.

    Returns the path to the created test file, or None if skipped/not needed.
    """
    cfg = PROJECT_BOOTSTRAP.get(project_type)
    if not cfg or not cfg.get("scaffold_test"):
        return None

    existing = find_existing_tests(project_dir, project_type)
    if existing:
        return None  # Tests already exist

    if not yes:
        click.echo(
            click.style(
                f"\n⚠  No tests found for {project_type} project in {project_dir}",
                fg="yellow",
            )
        )
        if not click.confirm(
            click.style("Create a sample test file?", fg="cyan"), default=True
        ):
            return None

    package_name = guess_package_name(project_dir, project_type)
    test_file = _resolve_scaffold_test_path(
        project_dir, project_type, cfg, package_name
    )
    if not test_file:
        return None

    if test_file.exists():
        return None

    test_file.parent.mkdir(parents=True, exist_ok=True)
    content = cfg["scaffold_test"].format(package_name=package_name)
    test_file.write_text(content, encoding="utf-8")

    click.echo(
        click.style(
            f"  ✓ Created sample test: {test_file.relative_to(project_dir)}", fg="green"
        )
    )
    return test_file


# =============================================================================
# High-level orchestration
# =============================================================================


def _new_bootstrap_result(project_dir: Path, project_type: str) -> Dict:
    return {
        "project_type": project_type,
        "project_dir": project_dir,
        "env_ok": False,
        "tests_found": [],
        "test_created": None,
        "doctor_report": None,
    }


def _pfix_auto_apply(project_dir: Path) -> bool:
    """Return the project's ``[tool.pfix] auto_apply`` setting.

    Defaults to ``True`` when pyproject.toml, the ``[tool.pfix]`` section, or the
    key is absent, so existing projects keep their behaviour. An explicit
    ``auto_apply = false`` lets a project opt out of automatic fixing/applying
    even in ``--all``/``--yes`` mode.
    """
    pyproject = Path(project_dir) / "pyproject.toml"
    if not pyproject.exists():
        return True
    tomllib = get_tomllib()
    if tomllib is None:
        return True
    try:
        content = pyproject.read_text(encoding="utf-8")
        data = tomllib.loads(content) if hasattr(tomllib, "loads") else None
        if data is None:
            with open(pyproject, "rb") as f:
                data = tomllib.load(f)
    except Exception:  # noqa: BLE001 - never let config parsing break the run
        return True
    pfix = (data.get("tool") or {}).get("pfix") or {}
    return bool(pfix.get("auto_apply", True))


def _coerce_bool(value) -> Optional[bool]:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        v = value.strip().lower()
        if v in {"1", "true", "yes", "on"}:
            return True
        if v in {"0", "false", "no", "off"}:
            return False
    return None


def _goal_yaml_auto_apply(project_dir: Path) -> Optional[bool]:
    """Read an auto-apply toggle from goal.yaml (works for any project type).

    Looks for top-level ``auto_apply`` / ``auto_fix`` or the same keys under
    ``advanced:``. Returns None when not set or unreadable.
    """
    config = Path(project_dir) / "goal.yaml"
    if not config.exists():
        return None
    try:
        import yaml  # lazy: goal already depends on pyyaml

        data = yaml.safe_load(config.read_text(encoding="utf-8")) or {}
    except Exception:  # noqa: BLE001 - config issues must not break the run
        return None
    if not isinstance(data, dict):
        return None
    for key in ("auto_apply", "auto_fix"):
        if key in data:
            return _coerce_bool(data[key])
    advanced = data.get("advanced")
    if isinstance(advanced, dict):
        for key in ("auto_apply", "auto_fix"):
            if key in advanced:
                return _coerce_bool(advanced[key])
    return None


def _auto_fix_enabled(project_dir: Path) -> bool:
    """Whether automatic fixing/applying is allowed for this project.

    Priority: ``GOAL_AUTO_FIX`` env var, then ``goal.yaml`` (project-type
    agnostic), then ``[tool.pfix] auto_apply`` in pyproject.toml. Defaults to
    True so existing projects are unaffected.
    """
    env = _coerce_bool(os.environ.get("GOAL_AUTO_FIX", ""))
    if env is not None:
        return env
    yaml_setting = _goal_yaml_auto_apply(project_dir)
    if yaml_setting is not None:
        return yaml_setting
    return _pfix_auto_apply(project_dir)


def _run_bootstrap_diagnostics(project_dir: Path, project_type: str, yes: bool):
    # Respect project settings even in --all/--yes mode: GOAL_AUTO_FIX env,
    # goal.yaml auto_apply/auto_fix, or [tool.pfix] auto_apply can opt out.
    auto_fix = yes and _auto_fix_enabled(project_dir)
    if yes and not auto_fix:
        click.echo(
            click.style(
                "  [tool.pfix] auto_apply = false -> skipping auto-fix (report only)",
                fg="yellow",
            )
        )
    click.echo(click.style(f"  DEBUG: auto_fix={auto_fix}", fg="magenta"))
    return diagnose_and_report(project_dir, project_type, auto_fix=auto_fix)


def _ensure_bootstrap_tests(
    project_dir: Path, project_type: str, yes: bool
) -> tuple[List[Path], Optional[Path]]:
    tests_found = find_existing_tests(project_dir, project_type)
    if tests_found:
        return tests_found, None

    test_created = scaffold_test(project_dir, project_type, yes=yes)
    if test_created:
        return [test_created], test_created
    return [], None


def bootstrap_project(project_dir: Path, project_type: str, yes: bool = False) -> Dict:
    """Full bootstrap: diagnose & fix config, ensure environment, scaffold tests.

    Returns a dict with status info:
        {
            'project_type': str,
            'project_dir': Path,
            'env_ok': bool,
            'tests_found': list[Path],
            'test_created': Path | None,
            'doctor_report': DoctorReport | None,
        }
    """
    result = _new_bootstrap_result(project_dir, project_type)

    # Step 1: Diagnose and auto-fix project configuration issues
    result["doctor_report"] = _run_bootstrap_diagnostics(project_dir, project_type, yes)

    # Step 1b: Ensure pfix is installed for auto-fixing errors
    _ensure_pfix_installed(project_dir, yes=yes)

    # Step 2: Ensure environment (venv, deps)
    # Note: For Python projects, this also installs the costs package
    result["env_ok"] = ensure_project_environment(project_dir, project_type, yes=yes)

    # Step 3: Find or scaffold tests
    result["tests_found"], result["test_created"] = _ensure_bootstrap_tests(
        project_dir, project_type, yes
    )

    return result


def bootstrap_all_projects(
    root: Optional[Path] = None, yes: bool = False
) -> List[Dict]:
    """Detect all project types (root + 1-level subfolders) and bootstrap each.

    Returns a list of bootstrap result dicts.
    """
    detected = detect_project_types_deep(root)
    if not detected:
        return []

    results = []
    for ptype, dirs in detected.items():
        for project_dir in dirs:
            try:
                rel = project_dir.relative_to(
                    root.resolve() if root else Path(".").resolve()
                )
            except ValueError:
                rel = project_dir
            click.echo(
                click.style(
                    f"\n📦 Bootstrapping {ptype} project in {rel}", fg="cyan", bold=True
                )
            )
            res = bootstrap_project(project_dir, ptype, yes=yes)
            results.append(res)

    return results


def _ensure_costs_installed(project_dir: Path, python_bin: str) -> bool:
    """Ensure costs package is installed and configured for AI tracking.

    Returns True if costs is ready to use.
    """
    if not _install_costs_package(project_dir, python_bin):
        return False

    _ensure_costs_config(project_dir)
    _ensure_env_template(project_dir)
    _generate_costs_badge(project_dir)

    return True


def _ensure_pfix_env(project_dir: Path) -> bool:
    """Ensure .env file exists with pfix API key template.

    Returns True if .env exists or was created.
    """
    env_file = project_dir / ".env"
    env_example = project_dir / ".env.example"

    # Template content for pfix .env
    env_template = """# pfix Configuration
# Self-healing Python — auto-fixes runtime errors via LLM

# Required: OpenRouter API key (https://openrouter.ai/keys)
OPENROUTER_API_KEY=

# Model (default: openrouter/qwen/qwen3-coder-next)
LLM_MODEL=openrouter/qwen/qwen3-coder-next

# Behavior
PFIX_AUTO_APPLY=true         # true = apply fixes without asking
PFIX_AUTO_INSTALL_DEPS=true   # true = auto pip/uv install
PFIX_AUTO_RESTART=false        # true = os.execv restart after fix
PFIX_MAX_RETRIES=3
PFIX_DRY_RUN=false
PFIX_ENABLED=true

# Git integration
PFIX_GIT_COMMIT=false         # true = auto-commit fixes
PFIX_GIT_PREFIX=pfix:         # commit message prefix

# Backup
PFIX_CREATE_BACKUPS=false     # false = disable .pfix_backups/ directory
"""

    _, existing_api_key = _find_openrouter_api_key(project_dir)
    if existing_api_key:
        return True

    created = False

    try:
        # Create .env from template if not exists
        if not env_file.exists():
            env_file.write_text(env_template, encoding="utf-8")
            click.echo(
                click.style(
                    "  ✓ Created .env template (add your OPENROUTER_API_KEY)",
                    fg="green",
                )
            )
            created = True

        # Also create .env.example (for git)
        if not env_example.exists():
            env_example.write_text(env_template, encoding="utf-8")

        # Ensure .env is in .gitignore
        gitignore = project_dir / ".gitignore"
        if gitignore.exists():
            gitignore_content = gitignore.read_text(encoding="utf-8")
            if ".env" not in gitignore_content:
                with open(gitignore, "a", encoding="utf-8") as f:
                    f.write("\n# Environment variables\n.env\n")
        else:
            gitignore.write_text(".env\n.env.local\n", encoding="utf-8")

        return True
    except OSError as e:
        logger.warning("Failed to create pfix env template in %s: %s", project_dir, e)
        click.echo(click.style(f"  ⚠ Could not create pfix .env: {e}", fg="yellow"))
        return False


def _validate_pfix_env(project_dir: Path) -> bool:
    """Validate that OPENROUTER_API_KEY is configured in .env.

    Shows error message if key is missing or empty.
    Returns True if key is present, False otherwise.
    """
    env_file, api_key = _find_openrouter_api_key(project_dir)
    if not env_file:
        env_file = project_dir / ".env"

    if not api_key:
        click.echo(
            click.style("\n  ⚠️ OPENROUTER_API_KEY not configured!", fg="red", bold=True)
        )
        click.echo(
            click.style(
                "  pfix requires an OpenRouter API key to fix errors.", fg="yellow"
            )
        )
        click.echo(click.style("\n  To fix this:", fg="cyan"))
        click.echo(
            click.style(
                "  1. Get your API key from: https://openrouter.ai/keys", fg="yellow"
            )
        )
        click.echo(click.style(f"  2. Add it to: {env_file}", fg="yellow"))
        click.echo(click.style("  3. Restart goal -a\n", fg="yellow"))
        return False

    # Check if key looks valid (starts with sk-or-v1-)
    if not api_key.startswith("sk-or-v1-"):
        click.echo(
            click.style(
                "\n  ⚠️ OPENROUTER_API_KEY format appears invalid!", fg="red", bold=True
            )
        )
        click.echo(click.style("  Expected format: sk-or-v1-...", fg="yellow"))
        click.echo(
            click.style(
                "\n  Please verify your API key at: https://openrouter.ai/keys",
                fg="cyan",
            )
        )
        return False

    click.echo(click.style("  ✓ OPENROUTER_API_KEY configured", fg="green"))
    return True


def _ensure_pfix_installed(project_dir: Path, yes: bool = False) -> bool:
    """Ensure pfix package is installed for auto-fixing errors.

    By default installs from PyPI. For local development, set
    GOAL_PFIX_LOCAL_PATH to install from a specific editable path.

    Returns True if pfix is ready to use.
    """
    python_bin = _find_python_bin(project_dir)

    # Check if pfix is already installed
    result = subprocess.run(
        [python_bin, "-c", "import pfix; print(pfix.__version__)"],
        capture_output=True,
        text=True,
        cwd=str(project_dir),
    )

    if result.returncode != 0:
        local_pfix_path = os.environ.get("GOAL_PFIX_LOCAL_PATH", "").strip()
        if local_pfix_path:
            local_pfix = Path(local_pfix_path).expanduser().resolve()
            if local_pfix.exists():
                click.echo(
                    click.style(
                        "  Installing pfix from configured local path...", fg="cyan"
                    )
                )
                install_cmd = [
                    python_bin,
                    "-m",
                    "pip",
                    "install",
                    "-e",
                    str(local_pfix),
                ]
            else:
                click.echo(
                    click.style(
                        f"  ⚠ GOAL_PFIX_LOCAL_PATH does not exist: {local_pfix}. Falling back to PyPI.",
                        fg="yellow",
                    )
                )
                click.echo(click.style("  Installing pfix from PyPI...", fg="cyan"))
                install_cmd = [python_bin, "-m", "pip", "install", "pfix>=0.1.60"]
        else:
            click.echo(click.style("  Installing pfix from PyPI...", fg="cyan"))
            install_cmd = [python_bin, "-m", "pip", "install", "pfix>=0.1.60"]

        install_result = subprocess.run(
            install_cmd, capture_output=True, text=True, cwd=str(project_dir)
        )
        if install_result.returncode != 0:
            click.echo(click.style("  ⚠ Could not install pfix package", fg="yellow"))
            return False
        click.echo(click.style("  ✓ Pfix package installed", fg="green"))
    else:
        click.echo(
            click.style(
                f"  ✓ Pfix package already installed ({result.stdout.strip()})",
                fg="green",
            )
        )

    # Check/add pfix config to pyproject.toml
    _ensure_pfix_config(project_dir, yes=yes)

    # Create .env template for API key if not exists
    env_ok = _ensure_pfix_env(project_dir)

    # Validate API key is configured
    if env_ok:
        _validate_pfix_env(project_dir)

    return True


def _ensure_pfix_config(project_dir: Path, yes: bool = False) -> bool:
    """Ensure [tool.pfix] section exists in pyproject.toml.

    Returns True if config was added or already exists.
    """
    pyproject = project_dir / "pyproject.toml"
    if not pyproject.exists():
        return False

    content = pyproject.read_text(encoding="utf-8")

    # Check if already configured
    if "[tool.pfix]" in content:
        return True

    # Add pfix configuration
    pfix_config = """\n[tool.pfix]
# Self-healing Python configuration
model = "openrouter/qwen/qwen3-coder-next"
auto_apply = true
auto_install_deps = true
auto_restart = false
max_retries = 3
create_backups = false
git_auto_commit = false

[tool.pfix.runtime_todo]
enabled = true
todo_file = "TODO.md"
min_severity = "low"
deduplicate = true
"""

    try:
        with open(pyproject, "a", encoding="utf-8") as f:
            f.write(pfix_config)
        click.echo(click.style("  ✓ Added [tool.pfix] to pyproject.toml", fg="green"))
        return True
    except OSError as e:
        logger.warning("Failed to append [tool.pfix] config to %s: %s", pyproject, e)
        click.echo(click.style(f"  ⚠ Could not add pfix config: {e}", fg="yellow"))
        return False


# Backward compatibility: delegate to new bootstrap module
def scaffold_test_file(project_dir: Path, project_type: str) -> bool:
    """Create a sample test file if none exist - delegates to bootstrap module."""
    return _scaffold_test_file_impl(project_dir, project_type)


__all__ = [
    "detect_project_types_deep",
    "guess_package_name",
    "ensure_project_environment",
    "refresh_test_dependencies",
    "scaffold_test_file",
    "bootstrap_project",
    "bootstrap_all_projects",
    "PROJECT_BOOTSTRAP",
]
